// Code generated by goctl. DO NOT EDIT.
package types

type FileInfo struct {
	Name string
	Body []byte
}

type UploadFileRequest struct {
	UserId string    `path:"userId"`
	Bucket string    `form:"bucket"`
	File   *FileInfo `form:"file,optional"`
}

type UserUploadFileResponse struct {
	FileId string `json:"fileId"`
}
