// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"goiot/apps/iotcore/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.ProcessReqRespMiddleware,
				serverCtx.ApiKeyMiddleware,
				serverCtx.AuthMiddleware,
			},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload/:userId",
					Handler: uploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/file"),
	)
}
