// Code generated by goctl. DO NOT EDIT.
// Source: iotCore.proto

package rpc

import (
	"context"

	"goiot/apps/iotcore/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadFileRequest  = pb.UploadFileRequest
	UploadFileResponse = pb.UploadFileResponse

	Rpc interface {
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := pb.NewRpcClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}
