// Code generated by goctl. DO NOT EDIT.
// Source: iotCore.proto

package server

import (
	"goiot/apps/iotcore/rpc/internal/logic"
	"goiot/apps/iotcore/rpc/internal/svc"
	"goiot/apps/iotcore/rpc/pb"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) UploadFile(stream pb.Rpc_UploadFileServer) error {
	l := logic.NewUploadFileLogic(stream.Context(), s.svcCtx)
	return l.UploadFile(stream)
}
