// Code generated by goctl. DO NOT EDIT.
// Source: iotCore.proto

package server

import (
	"context"

	"goiot/apps/iotcore/rpc/internal/logic"
	"goiot/apps/iotcore/rpc/internal/svc"
	"goiot/apps/iotcore/rpc/pb"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) UploadFile(ctx context.Context, in *pb.UploadFileRequest) (*pb.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
