// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10001]
	_ = x[ParamError-10002]
	_ = x[FileError-10003]
	_ = x[TooMandyRequests-10004]
	_ = x[APIKeyAuthFail-10005]
	_ = x[TokenAuthFail-20001]
	_ = x[TokenIsNotExist-20002]
	_ = x[AccessTokenExpiredError-20003]
	_ = x[RefreshTokenExpiredError-20004]
}

const (
	_ErrCode_name_0 = "服务内部错误参数信息有误上传的文件有误请求频率超出限制API Key校验失败"
	_ErrCode_name_1 = "Token鉴权失败TokenIsNotExistAccessTokenExpiredErrorRefreshTokenExpiredError"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 18, 36, 57, 81, 100}
	_ErrCode_index_1 = [...]uint8{0, 17, 32, 55, 79}
)

func (i ErrCode) String() string {
	switch {
	case 10001 <= i && i <= 10005:
		i -= 10001
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 20001 <= i && i <= 20004:
		i -= 20001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
